CREATE TABLE IF NOT EXISTS trino_queries (
  query_id VARCHAR(255) NOT NULL PRIMARY KEY,
  transaction_id VARCHAR(255) NULL,
  query MEDIUMTEXT NOT NULL,
  update_type VARCHAR(255) NULL,
  prepared_query MEDIUMTEXT NULL,
  query_state VARCHAR(255) NOT NULL,
  plan MEDIUMTEXT NULL,
  stage_info_json MEDIUMTEXT NULL,
  user VARCHAR(255) NOT NULL,
  principal VARCHAR(255) NULL,
  trace_token VARCHAR(255) NULL,
  remote_client_address VARCHAR(255) NULL,
  user_agent VARCHAR(255) NULL,
  client_info VARCHAR(255) NULL,
  client_tags_json MEDIUMTEXT NOT NULL,
  source VARCHAR(255) NULL,
  catalog VARCHAR(255) NULL,
  `schema` VARCHAR(255) NULL,
  resource_group_id VARCHAR(255) NULL,
  session_properties_json MEDIUMTEXT NOT NULL,
  server_address VARCHAR(255) NOT NULL,
  server_version VARCHAR(255) NOT NULL,
  environment VARCHAR(255) NOT NULL,
  query_type VARCHAR(255) NULL,
  inputs_json MEDIUMTEXT NOT NULL,
  output_json MEDIUMTEXT NULL,
  error_code VARCHAR(255) NULL,
  error_type VARCHAR(255) NULL,
  failure_type VARCHAR(255) NULL,
  failure_message MEDIUMTEXT NULL,
  failure_task VARCHAR(255) NULL,
  failure_host VARCHAR(255) NULL,
  failures_json MEDIUMTEXT NULL,
  warnings_json MEDIUMTEXT NOT NULL,
  cpu_time_millis BIGINT NOT NULL,
  failed_cpu_time_millis BIGINT NOT NULL,
  wall_time_millis BIGINT NOT NULL,
  queued_time_millis BIGINT NOT NULL,
  scheduled_time_millis BIGINT NOT NULL,
  failed_scheduled_time_millis BIGINT NOT NULL,
  waiting_time_millis BIGINT NOT NULL,
  analysis_time_millis BIGINT NOT NULL,
  planning_time_millis BIGINT NOT NULL,
  planning_cpu_time_millis BIGINT NOT NULL,
  starting_time_millis BIGINT NOT NULL,
  execution_time_millis BIGINT NOT NULL,
  input_blocked_time_millis BIGINT NOT NULL,
  failed_input_blocked_time_millis BIGINT NOT NULL,
  output_blocked_time_millis BIGINT NOT NULL,
  failed_output_blocked_time_millis BIGINT NOT NULL,
  physical_input_read_time_millis BIGINT NOT NULL,
  peak_memory_bytes BIGINT NOT NULL,
  peak_task_memory_bytes BIGINT NOT NULL,
  physical_input_bytes BIGINT NOT NULL,
  physical_input_rows BIGINT NOT NULL,
  internal_network_bytes BIGINT NOT NULL,
  internal_network_rows BIGINT NOT NULL,
  total_bytes BIGINT NOT NULL,
  total_rows BIGINT NOT NULL,
  output_bytes BIGINT NOT NULL,
  output_rows BIGINT NOT NULL,
  written_bytes BIGINT NOT NULL,
  written_rows BIGINT NOT NULL,
  cumulative_memory DOUBLE NOT NULL,
  failed_cumulative_memory DOUBLE NOT NULL,
  completed_splits BIGINT NOT NULL,
  retry_policy VARCHAR(255) NOT NULL,
  operator_summaries_json MEDIUMTEXT NOT NULL
)
DEFAULT CHARACTER SET utf8
